import { TourId, TourStep } from './tourTypes';

// ─────────────────────────────────────────────────────────────────────────────
// Tur senaryoları v2 — az yazı, aşamalı anlatım. Metinler kullanıcı onaylı
// olanlarda BİREBİR korunur (p-welcome, t-finish gövdesi, j-profile gövdesi).
// data-tour-id hedefleri ilgili bileşenlerde. Sahalar turu son adımda Takım
// turuna ZİNCİRLENİR (chainTo).
// ─────────────────────────────────────────────────────────────────────────────

export const TOUR_SCRIPTS: Record<TourId, TourStep[]> = {
    pitches: [
        {
            id: 'p-welcome',
            icon: 'welcome',
            title: 'TANITIM TURU',
            body: "Dimli'ye hoş geldin! 1 dakikada uygulamayı tanıyalım.",
            advance: 'next',
            nextLabel: 'Başla',
            backdrop: 'dark', // yalnız karşılamada sayfa karartılır (kullanıcı kararı)
        },
        {
            id: 'p-explore',
            icon: 'pitch',
            title: 'SAHALARI KEŞFET',
            body: 'Yakınındaki sahalar bu sayfada listelenir. Sana en uygun sahayı fiyat, yakınlık, müsaitlik durumu ve değerlendirme puanına göre belirleyebilirsin.',
            advance: 'next',
        },
        {
            id: 'p-filters',
            frame: 'lines',
            target: 'pitch-filters',
            icon: 'filter',
            title: 'FİLTRELER',
            body: 'Yakınlık mesafesini buradan ayarlarsın; Tarih seç, Sırala ile sana uygun filtreye göre sahaları diz.',
            advance: 'next',
        },
        {
            id: 'p-demo-card',
            target: 'demo-business-card',
            icon: 'pitch',
            title: 'TANITIM SAHASI',
            body: 'Bu örnek işletme üzerinden deneyeceğiz. Karta dokun.',
            advance: 'target-tap',
        },
        {
            id: 'p-pitch-tabs',
            target: 'demo-pitch-tabs',
            icon: 'pitch',
            title: 'SAHALAR ARASI GEÇİŞ',
            body: 'İşletmenin birden fazla sahası olabilir — sekmelerden 1 Nolu / 2 Nolu saha arasında geçiş yapabilirsin.',
            advance: 'next',
        },
        {
            id: 'p-slots',
            compact: true,
            target: 'demo-slot-grid',
            icon: 'clock',
            title: 'SAAT AKIŞI',
            body: 'Sahanın müsaitlik durumunu buradan kontrol et. Saatlerin durumu renklerle gösterilir: Boş, Dolu, Onay Bekliyor, Rakip Aranıyor.',
            advance: 'next',
        },
        {
            id: 'p-facilities',
            target: 'demo-facilities',
            icon: 'shield',
            title: 'İMKANLAR',
            body: 'Sahanın sunduğu imkanlar burada yer alıyor.',
            advance: 'next',
        },
        {
            id: 'p-matches',
            target: 'demo-active-matches',
            icon: 'megaphone',
            title: 'BURADA RAKİP ARAYANLAR',
            body: 'Bu sahada rakip arayan takımları gör, onlara maç teklif et.',
            advance: 'next',
        },
        {
            id: 'p-slot-2000',
            target: 'demo-slot-2000',
            icon: 'clock',
            title: '20:00 BOŞ',
            body: 'Dokun, maç kur.',
            advance: 'event',
            eventId: 'demo-create-modal-open',
        },
        {
            id: 'p-type-rakip',
            target: 'demo-type-rakip',
            icon: 'megaphone',
            title: 'RAKİP ARANIYOR',
            body: "Rakip bulmak için ilan yayınlanır. Maç Pazarı'ndan yakınındaki ilanlara da meydan okuyabilirsin.",
            advance: 'next',
            spotlightPadding: 10,
        },
        {
            id: 'p-type-kendi',
            target: 'demo-type-kendi',
            icon: 'shield',
            title: 'KENDİ ARAMIZDA',
            body: 'Saha yalnız takımın için ayrılır; işletme onayıyla kesinleşir.',
            footnote: 'Gerçekte ilan açmak için takım kaptanı ya da yardımcı kaptanı olman gerekir — şimdilik örnek takımınla deniyorsun.',
            advance: 'next',
            spotlightPadding: 10,
        },
        {
            id: 'p-submit',
            target: 'demo-submit',
            icon: 'flag',
            title: 'İLANI YAYINLA',
            body: '"Kendi Aramızda" seçili. Butona dokun.',
            footnote: 'Bu bir tanıtım — gerçek bir ilan yayınlanmaz.',
            advance: 'event',
            eventId: 'demo-ad-submitted',
        },
        {
            id: 'p-chat-status',
            target: 'demo-chat-status',
            icon: 'chat',
            title: 'ONAY BEKLİYOR',
            body: 'Takımın için maç sohbeti açıldı. Rezervasyon işletme onayı bekliyor — onaylanınca Kesinleşti olur.',
            advance: 'next',
            spotlightPadding: 12,
        },
        {
            id: 'p-chat-system',
            target: 'demo-chat-system',
            icon: 'phone',
            title: 'MAÇI KESİNLEŞTİR',
            body: 'Maçı garantiye almak için işletmeyi arayıp teyit et.',
            advance: 'next',
        },
        {
            id: 'p-chat-msgs',
            target: 'demo-chat-messages',
            icon: 'chat',
            title: 'MAÇ SOHBETİ',
            body: 'Maçtan önce arkadaşlarınla maçın hikayesini burada yaz.',
            advance: 'next',
        },
        {
            id: 'p-go-team',
            target: 'nav-team',
            icon: 'team',
            title: 'ŞİMDİ TAKIMINI KUR!',
            body: 'Alt menüden TAKIM sekmesine dokun.',
            advance: 'target-tap',
            onEnter: 'close-demo-chat',
            spotlightPadding: 10,
            chainTo: 'team',
        },
    ],
    // Derin Takımım turu: "Örnek Takımım" demo takımıyla tüm özellikler gezdirilir;
    // finalde demo gizlenir ve gerçek "Takım Kur" spotlight'lanır (kullanıcı kararı).
    team: [
        {
            id: 't-tabs',
            target: 'team-tabs',
            icon: 'team',
            title: 'PROFİLİM / TAKIMIM',
            body: 'Profilim: oyuncu kartın. Takımım: takım yönetimi.',
            advance: 'next',
        },
        {
            id: 't-tab-team',
            target: 'team-tab-takimim',
            icon: 'shield',
            title: 'TAKIMIM',
            body: 'Sekmeye dokun — örnek takımınla gezeceğiz.',
            advance: 'target-tap',
        },
        {
            id: 't-header',
            target: 'team-header',
            icon: 'team',
            title: 'TAKIM KARTIN',
            body: 'Takım adı, seviye ve fair-play puanı burada.',
            footnote: 'Bu bir tanıtım takımı — tur bitince kendi takımını kuracaksın.',
            advance: 'next',
        },
        {
            id: 't-code',
            target: 'team-code',
            icon: 'user-plus',
            title: 'TAKIM KODU',
            body: 'Arkadaşların bu kodla takımını bulup katılabilir — dokunup kopyalayabilirsin.',
            advance: 'next',
            spotlightPadding: 10,
        },
        {
            id: 't-stats',
            target: 'team-stats',
            icon: 'clock',
            title: 'İSTATİSTİKLER',
            body: 'Oynanan maç, fair-play ve değerlendirme sayısı.',
            advance: 'next',
        },
        {
            id: 't-upcoming',
            target: 'team-btn-upcoming',
            icon: 'clock',
            title: 'YAKLAŞAN MAÇLAR',
            body: 'Dokun — kesinleşmiş maçlarını gör.',
            advance: 'target-tap',
        },
        {
            id: 't-upcoming-in',
            compact: true,
            target: 'team-upcoming-item',
            icon: 'flag',
            title: 'KESİNLEŞMİŞ MAÇ',
            body: 'İşletme onayladı, saha senin! Kesinleşmiş maçların burada listelenir.',
            advance: 'next',
        },
        {
            id: 't-upcoming-close',
            target: 'team-upcoming-close',
            icon: 'clock',
            title: 'KAPAT',
            body: 'Devam etmek için kapat.',
            advance: 'target-tap',
        },
        {
            id: 't-requests',
            target: 'team-btn-requests',
            icon: 'megaphone',
            title: 'TAKIM İSTEKLERİ',
            body: 'Dokun — gönderdiğin istekleri gör.',
            advance: 'target-tap',
        },
        {
            id: 't-requests-in',
            compact: true,
            target: 'team-requests-list',
            icon: 'megaphone',
            title: 'İSTEKLERİN BURADA',
            body: 'Meydan okumaların ve joker davetlerin burada — Oyuncu 1\'e yolladığın davet de sekmede bekliyor.',
            advance: 'next',
        },
        {
            id: 't-requests-joker-tab',
            target: 'team-requests-joker-tab',
            icon: 'zap',
            title: 'JOKER DAVETLERİ',
            body: 'Sekmeye dokun.',
            advance: 'target-tap',
        },
        {
            id: 't-requests-joker-in',
            compact: true,
            target: 'team-requests-list',
            icon: 'zap',
            title: 'JOKER DAVETİN',
            body: 'Oyuncu 1\'e gönderdiğin joker daveti burada — durumunu izler, gerekirse geri çekersin.',
            advance: 'next',
        },
        {
            id: 't-requests-close',
            target: 'team-requests-close',
            icon: 'clock',
            title: 'KAPAT',
            body: 'Devam etmek için kapat.',
            advance: 'target-tap',
        },
        {
            id: 't-history',
            target: 'team-btn-history',
            icon: 'clock',
            title: 'GEÇMİŞ MAÇLAR',
            body: 'Dokun — oynadığın maçları gör.',
            advance: 'target-tap',
        },
        {
            id: 't-history-rate',
            target: 'team-history-rate',
            icon: 'flag',
            title: 'DEĞERLENDİR',
            body: 'Bu maç puan bekliyor — Değerlendir\'e dokun.',
            advance: 'target-tap',
        },
        {
            id: 't-rating',
            compact: true,
            target: 'team-rating-modal',
            icon: 'flag',
            title: 'YILDIZINI VER',
            body: 'İşletmeye ve rakibe yıldız ver, Gönder\'e dokun. Değerlendirmeler topluluğu güvenilir tutar.',
            footnote: 'Bu bir tanıtım — değerlendirme kaydedilmez.',
            advance: 'event',
            eventId: 'demo-rating-submitted',
        },
        {
            id: 't-history-close',
            target: 'team-history-close',
            icon: 'clock',
            title: 'KAPAT',
            body: 'Devam etmek için kapat.',
            advance: 'target-tap',
        },
        {
            id: 't-home',
            target: 'team-home-business',
            icon: 'pitch',
            title: 'EV SAHİBİ SAHA',
            body: 'Takımının favori işletmesini seç — İlan Oluştur ile tek dokunuşta maç kur.',
            advance: 'next',
        },
        {
            id: 't-add-player',
            target: 'team-add-player',
            icon: 'user-plus',
            title: 'OYUNCU EKLE',
            body: 'Dokun — kadronu güçlendir.',
            advance: 'target-tap',
        },
        {
            id: 't-invite-link',
            compact: true,
            target: 'team-invite-share',
            icon: 'user-plus',
            title: 'DAVET LİNKİ',
            body: 'Davet linkini arkadaşlarınla paylaş — tek dokunuşla takımına katılırlar.',
            advance: 'next',
        },
        {
            id: 't-addplayer-close',
            target: 'team-addplayer-close',
            icon: 'clock',
            title: 'KAPAT',
            body: 'Devam etmek için kapat.',
            advance: 'target-tap',
        },
        {
            id: 't-vice',
            target: 'team-player-vice',
            icon: 'shield',
            title: 'YARDIMCI KAPTAN',
            body: 'Oyuncu satırındaki menüden yardımcı kaptan atayabilirsin — kaptanla aynı yetkilere sahip olurlar.',
            advance: 'next',
        },
        {
            id: 't-finish',
            target: 'team-create-btn',
            icon: 'flag',
            title: 'ŞİMDİ SIRA SENDE!',
            body: 'Tanıtım bitti — kendi takımını kur ya da takım koduyla bir takıma katıl. Sahaları keşfet, sana en uygun sahada rakibini bul ya da kendi aranızda maçını oluştur.',
            footnote: "İstersen takım kurmadan, sadece joker modunu aktif ederek de maçlara katılabilirsin. Turları istediğin zaman Hesap Ayarları → Uygulama Tanıtımı'ndan tekrar izleyebilirsin.",
            advance: 'next',
            nextLabel: 'Bitir',
            onEnter: 'hide-demo-team',
        },
    ],
    // Maç Pazarı turu: Dimli United demo ilanı + işletme/takım modalları + filtreler
    marketplace: [
        {
            id: 'm-welcome',
            icon: 'megaphone',
            title: 'MAÇ PAZARI',
            body: 'Yakınındaki rakip arayan takımların ilanları burada listelenir.',
            advance: 'next',
            nextLabel: 'Başla',
        },
        {
            id: 'm-filters',
            frame: 'lines',
            target: 'marketplace-filters',
            icon: 'filter',
            title: 'FİLTRELER',
            body: 'Tarihe, konuma ve sıralamaya göre ilanları filtrele.',
            footnote: 'Takımın olduğunda kendi ilanlarını gizleme seçeneği de burada görünür.',
            advance: 'next',
        },
        {
            id: 'm-demo-card',
            compact: true,
            target: 'market-demo-card',
            icon: 'megaphone',
            title: 'TANITIM İLANI',
            body: 'Dimli United rakip arıyor — ilanda takım, saha, tarih ve ücret bilgisi var.',
            advance: 'next',
        },
        {
            id: 'm-venue',
            target: 'market-demo-venue',
            icon: 'pitch',
            title: 'SAHA BİLGİSİ',
            body: 'Saha adına dokun — işletme bilgisi açılır.',
            advance: 'target-tap',
        },
        {
            id: 'm-venue-in',
            compact: true,
            target: 'market-business-modal',
            icon: 'pitch',
            title: 'İŞLETME KARTI',
            body: 'Sahanın fotoğrafı, fiyatı, imkanları ve konumu burada.',
            advance: 'next',
        },
        {
            id: 'm-venue-close',
            target: 'market-business-close',
            icon: 'clock',
            title: 'KAPAT',
            body: 'Devam etmek için kapat.',
            advance: 'target-tap',
        },
        {
            id: 'm-team',
            target: 'market-demo-team',
            icon: 'team',
            title: 'TAKIM KARTI',
            body: 'Takım adına dokun — takım bilgi kartı açılır.',
            advance: 'target-tap',
        },
        {
            id: 'm-team-in',
            compact: true,
            target: 'market-team-modal',
            icon: 'team',
            title: 'RAKİBİNİ TANI',
            body: 'Takımın seviyesi, fair-play puanı ve kadrosu burada — rakibini maçtan önce tanı.',
            advance: 'next',
        },
        {
            id: 'm-team-close',
            target: 'market-team-close',
            icon: 'clock',
            title: 'KAPAT',
            body: 'Devam etmek için kapat.',
            advance: 'target-tap',
        },
        {
            id: 'm-finish',
            icon: 'flag',
            title: 'HAZIRSIN!',
            body: 'Takım kaptanı olduğunda ilanlara "Meydan Oku" ile teklif gönderebilirsin. İlk ilanı Sahalar sayfasından sen de açabilirsin.',
            advance: 'next',
            nextLabel: 'Bitir',
        },
    ],
    jokers: [
        {
            id: 'j-welcome',
            icon: 'zap',
            title: 'JOKER HAVUZU',
            body: 'Joker oyuncular, eksik kadroları 1 maçlığına tamamlar. Yakınındakiler bu sayfada.',
            advance: 'next',
            nextLabel: 'Başla',
        },
        {
            id: 'j-profile',
            target: 'joker-profile-btn',
            icon: 'zap',
            title: 'PROFİLİNİ EKLE',
            body: 'Joker oyuncu kartını aktif et. 1 maçlığına başka takımlar için oyna.',
            advance: 'next',
        },
        {
            id: 'j-card',
            target: 'joker-first-card',
            icon: 'user-plus',
            title: 'EKSİK OYUNCUYU TAMAMLA',
            body: 'Oyuncu 1 örnek bir joker. Kartına dokun.',
            advance: 'target-tap',
        },
        {
            id: 'j-invite',
            target: 'joker-invite-btn',
            icon: 'user-plus',
            title: 'MAÇA DAVET ET',
            body: 'Kaptanlar ve yardımcı kaptanlar, jokerleri yaklaşan maçlarına davet edebilir. Butona dokun.',
            advance: 'target-tap',
            spotlightPadding: 10,
        },
        {
            id: 'j-match',
            target: 'joker-demo-match',
            icon: 'pitch',
            title: 'MAÇI SEÇ',
            body: 'Dimli Halı Saha maçını seç.',
            advance: 'target-tap',
        },
        {
            id: 'j-send',
            target: 'joker-send-invite',
            icon: 'flag',
            title: 'DAVETİ GÖNDER',
            body: 'Daveti gönder — Oyuncu 1 kabul ederse bildirim alırsın.',
            footnote: 'Bu bir tanıtım — gerçek bir davet gönderilmez.',
            advance: 'event',
            eventId: 'demo-joker-invited',
        },
        {
            id: 'j-finish',
            icon: 'chat',
            title: 'DAVET İLETİLDİ!',
            body: 'Davetler maç sohbetin üzerinden yürür — joker kabul edince seninle müzakere sohbeti açılır.',
            footnote: 'Joker davetlerini Takım İstekleri bölümünden toplu yönetebilirsin.',
            advance: 'next',
            nextLabel: 'Bitir',
        },
    ],
};
