import { TourId, TourStep } from './tourTypes';

// ─────────────────────────────────────────────────────────────────────────────
// Tur senaryoları v2 — az yazı, aşamalı anlatım. Metinler kullanıcı onaylı
// olanlarda BİREBİR korunur (p-welcome, t-finish gövdesi, j-profile gövdesi).
// data-tour-id hedefleri ilgili bileşenlerde. Sahalar turu son adımda Takım
// turuna ZİNCİRLENİR (chainTo).
// ─────────────────────────────────────────────────────────────────────────────

export const TOUR_SCRIPTS: Record<TourId, TourStep[]> = {
    pitches: [
        {
            id: 'p-welcome',
            icon: 'welcome',
            title: 'TANITIM TURU',
            body: "Dimli'ye hoş geldin! 1 dakikada uygulamayı tanıyalım.",
            advance: 'next',
            nextLabel: 'Başla',
            backdrop: 'dark', // yalnız karşılamada sayfa karartılır (kullanıcı kararı)
        },
        {
            id: 'p-explore',
            icon: 'pitch',
            title: 'SAHALARI KEŞFET',
            body: 'Yakınındaki sahalar bu sayfada listelenir. Sana en uygun sahayı fiyat, yakınlık, müsaitlik durumu ve değerlendirme puanına göre belirleyebilirsin.',
            advance: 'next',
        },
        {
            id: 'p-filters',
            target: 'pitch-filters',
            icon: 'filter',
            title: 'FİLTRELER',
            body: 'Yakınlık mesafesini buradan ayarlarsın; Tarih seç, Sırala ile sana uygun filtreye göre sahaları diz.',
            advance: 'next',
        },
        {
            id: 'p-demo-card',
            target: 'demo-business-card',
            icon: 'pitch',
            title: 'TANITIM SAHASI',
            body: 'Bu örnek işletme üzerinden deneyeceğiz. Karta dokun.',
            advance: 'target-tap',
        },
        {
            id: 'p-pitch-tabs',
            target: 'demo-pitch-tabs',
            icon: 'pitch',
            title: 'SAHALAR ARASI GEÇİŞ',
            body: 'İşletmenin birden fazla sahası olabilir — sekmelerden 1 Nolu / 2 Nolu saha arasında geçiş yapabilirsin.',
            advance: 'next',
        },
        {
            id: 'p-slots',
            target: 'demo-slot-grid',
            icon: 'clock',
            title: 'SAAT AKIŞI',
            body: 'Sahanın müsaitlik durumunu buradan kontrol et. Saatlerin durumu renklerle gösterilir: Boş, Dolu, Onay Bekliyor, Rakip Aranıyor.',
            advance: 'next',
        },
        {
            id: 'p-facilities',
            target: 'demo-facilities',
            icon: 'shield',
            title: 'İMKANLAR',
            body: 'Sahanın sunduğu imkanlar burada yer alıyor.',
            advance: 'next',
        },
        {
            id: 'p-matches',
            target: 'demo-active-matches',
            icon: 'megaphone',
            title: 'BURADA RAKİP ARAYANLAR',
            body: 'Bu sahada rakip arayan takımları gör, onlara maç teklif et.',
            advance: 'next',
        },
        {
            id: 'p-slot-2000',
            target: 'demo-slot-2000',
            icon: 'clock',
            title: '20:00 BOŞ',
            body: 'Dokun, maç kur.',
            advance: 'event',
            eventId: 'demo-create-modal-open',
        },
        {
            id: 'p-type-rakip',
            target: 'demo-type-rakip',
            icon: 'megaphone',
            title: 'RAKİP ARANIYOR',
            body: "Rakip bulmak için ilan yayınlanır. Maç Pazarı'ndan yakınındaki ilanlara da meydan okuyabilirsin.",
            advance: 'next',
            spotlightPadding: 10,
        },
        {
            id: 'p-type-kendi',
            target: 'demo-type-kendi',
            icon: 'shield',
            title: 'KENDİ ARAMIZDA',
            body: 'Saha yalnız takımın için ayrılır; işletme onayıyla kesinleşir.',
            footnote: 'Gerçekte ilan açmak için takım kaptanı ya da yardımcı kaptanı olman gerekir — şimdilik örnek takımınla deniyorsun.',
            advance: 'next',
            spotlightPadding: 10,
        },
        {
            id: 'p-submit',
            target: 'demo-submit',
            icon: 'flag',
            title: 'İLANI YAYINLA',
            body: '"Kendi Aramızda" seçili. Butona dokun.',
            advance: 'event',
            eventId: 'demo-ad-submitted',
        },
        {
            id: 'p-chat-status',
            target: 'demo-chat-status',
            icon: 'chat',
            title: 'ONAY BEKLİYOR',
            body: 'Takımın için maç sohbeti açıldı. Rezervasyon işletme onayı bekliyor — onaylanınca Kesinleşti olur.',
            advance: 'next',
            spotlightPadding: 12,
        },
        {
            id: 'p-chat-system',
            target: 'demo-chat-system',
            icon: 'phone',
            title: 'MAÇI KESİNLEŞTİR',
            body: 'Maçı garantiye almak için işletmeyi arayıp teyit et.',
            advance: 'next',
        },
        {
            id: 'p-chat-msgs',
            target: 'demo-chat-messages',
            icon: 'chat',
            title: 'MAÇ SOHBETİ',
            body: 'Maçtan önce arkadaşlarınla maçın hikayesini burada yaz.',
            advance: 'next',
        },
        {
            id: 'p-go-team',
            target: 'nav-team',
            icon: 'team',
            title: 'ŞİMDİ TAKIMINI KUR!',
            body: 'Alt menüden TAKIM sekmesine dokun.',
            advance: 'target-tap',
            onEnter: 'close-demo-chat',
            spotlightPadding: 10,
            chainTo: 'team',
        },
    ],
    team: [
        {
            id: 't-tabs',
            target: 'team-tabs',
            icon: 'team',
            title: 'PROFİLİM / TAKIMIM',
            body: 'Profilim: oyuncu kartın. Takımım: takım yönetimi.',
            advance: 'next',
        },
        {
            id: 't-tab-team',
            target: 'team-tab-takimim',
            icon: 'shield',
            title: 'TAKIMIM',
            body: 'Sekmeye dokun.',
            advance: 'target-tap',
        },
        {
            id: 't-create',
            target: 'team-create-btn',
            icon: 'user-plus',
            title: 'TAKIM KUR',
            body: 'Takımını kur, kaptan ol — ya da Takım Bul ile mevcut bir takıma katıl.',
            advance: 'next',
        },
        {
            id: 't-finish',
            icon: 'flag',
            title: 'HAZIRSIN!',
            body: 'Hazırsın! Önce Takım sekmesinden takımını kur, sahaları keşfet. Sana en uygun sahada rakibini bul ya da kendi aranızda maçını oluştur.',
            footnote: "Turları istediğin zaman Hesap Ayarları → Uygulama Tanıtımı bölümünden tekrar izleyebilirsin.",
            advance: 'next',
            nextLabel: 'Bitir',
        },
    ],
    jokers: [
        {
            id: 'j-welcome',
            icon: 'zap',
            title: 'JOKER HAVUZU',
            body: 'Joker oyuncular, eksik kadroları 1 maçlığına tamamlar. Yakınındakiler bu sayfada.',
            advance: 'next',
            nextLabel: 'Başla',
        },
        {
            id: 'j-profile',
            target: 'joker-profile-btn',
            icon: 'zap',
            title: 'PROFİLİNİ EKLE',
            body: 'Joker oyuncu kartını aktif et. 1 maçlığına başka takımlar için oyna.',
            advance: 'next',
        },
        {
            id: 'j-card',
            target: 'joker-first-card',
            icon: 'user-plus',
            title: 'EKSİK OYUNCUYU TAMAMLA',
            body: 'Oyuncu 1 örnek bir joker. Kartına dokun.',
            advance: 'target-tap',
        },
        {
            id: 'j-invite',
            target: 'joker-invite-btn',
            icon: 'user-plus',
            title: 'MAÇA DAVET ET',
            body: 'Kaptanlar ve yardımcı kaptanlar, jokerleri yaklaşan maçlarına davet edebilir. Butona dokun.',
            advance: 'target-tap',
            spotlightPadding: 10,
        },
        {
            id: 'j-match',
            target: 'joker-demo-match',
            icon: 'pitch',
            title: 'MAÇI SEÇ',
            body: 'Dimli Halı Saha maçını seç.',
            advance: 'target-tap',
        },
        {
            id: 'j-send',
            target: 'joker-send-invite',
            icon: 'flag',
            title: 'DAVETİ GÖNDER',
            body: 'Daveti gönder — Oyuncu 1 kabul ederse bildirim alırsın.',
            advance: 'event',
            eventId: 'demo-joker-invited',
        },
        {
            id: 'j-finish',
            icon: 'chat',
            title: 'DAVET İLETİLDİ!',
            body: 'Davetler maç sohbetin üzerinden yürür — joker kabul edince seninle müzakere sohbeti açılır.',
            footnote: 'Joker davetlerini Takım İstekleri bölümünden toplu yönetebilirsin.',
            advance: 'next',
            nextLabel: 'Bitir',
        },
    ],
};
